# Generated by Django 5.2.7 on 2025-10-21 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_product'),
        ('user', '0003_whislist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ordertb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('orderdate', models.CharField(max_length=20)),
                ('carrier', models.CharField(blank=True, max_length=20, null=True)),
                ('tracking', models.CharField(blank=True, max_length=20, null=True)),
                ('shippingdate', models.CharField(blank=True, max_length=18, null=True)),
                ('transactionid', models.CharField(blank=True, max_length=20, null=True)),
                ('paymentdate', models.CharField(blank=True, max_length=18, null=True)),
                ('paymentstatus', models.CharField(default='pending', max_length=20)),
                ('orderstatus', models.CharField(default='pending', max_length=18)),
                ('ordertotal', models.IntegerField()),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='orderitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('count', models.IntegerField()),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ordertb')),
            ],
        ),
    ]
