# Generated by Django 5.2.7 on 2025-10-17 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('fabric', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('listprice', models.FloatField()),
                ('price', models.FloatField()),
                ('price50', models.FloatField()),
                ('price100', models.FloatField()),
                ('image', models.FileField(upload_to='media')),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.category')),
            ],
        ),
    ]
